### PR TITLE
Facet 101

### PR DESCRIPTION
**Pull request by lesjoneshmrc**
Do not merge, yet.

### CODE REVIEW

**Comment by CEPoole** [comment]
:1st_place_medal:

**Comment by CEPoole** [comment]
Can't merge in good faith as `when supplying a valid query and requesting page 3 should return a 200 and the sic code descriptions skipping pages 1 & 2` is consistently failing on my machine ¯\_(ツ)_/¯

**Comment by lesjoneshmrc** [comment]
Good spot - that's as a result of mixing two changes - which we shouldn't do. I'll regress the uplift to 7.1.0 and raise a separate PR for that.

**Comment by lesjoneshmrc** [comment]
@CEPoole Can you pull & re-test please?

**Pull request merged**
